### ISSUE TITLE
jar file release please

### ISSUE THREAD

**Issue by Adam1609** [larryTheCoder/ASkyBlock-Nukkit#1]
Could you compile and release please :)

**Comment by larryTheCoder** [comment]
I not really yet to compile a Buggy Plugin right now please wait : )

**Comment by larryTheCoder** [comment]
Here you go [ASkyBlock](https://drive.google.com/open?id=0Bw94aKEUd_98WHM0dWNzaVpDaFk) compiled latest source code has been made.

Usage: /is - Create an island
Usage: /is generate

More comming soon

**Comment by iDirtniverse** [comment]
Hi could you please compile the latest update version? when I run MVN Package theres an error on two files, which I renamed the file to correct class but after I compiled it theres error with SQL databases, is there anyway to disable the features or is it permanent. If you can compile with complete and no errors made when plugin is loaded please release it! thank you so much for doing an amazing job toward the community!
