### ISSUE TITLE
Final Update? :D

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/ASkyBlock-Nukkit#14]
Island wont disappear when /is delete executed 
Reward for challenges ? 👍 

And plugin is ready? @larryTheCoder 

Update today?

**Comment by larryTheCoder** [comment]
I will do 👍

**Comment by NycuRO** [comment]
Today? @larryTheCoder

**Comment by larryTheCoder** [comment]
I am busy currently today 
I will upload it on Saturday GMT:+8.00

**Comment by sindronik** [comment]
@larryTheCoder  The / is delete command does not work and /is tgg help 
Critical error MCPE 1.0.7, Nukkit build #587

**Comment by NycuRO** [comment]
@larryTheCoder Now? :D

**Comment by NycuRO** [comment]
@larryTheCoder You says end..

**Comment by larryTheCoder** [comment]
@NycuRO don't be upset, I am trying the best to upload the latest file 👍
