### ISSUE TITLE
Server freezing

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#25]
### Issue Description
When I try to go to my skyblock second time when I type /is server freeze about half minute then it say: Your island could not be found! Error?

### Steps to Reproduce the Issue

1. Create your SkyBlock
2. Back to spawn
3. Type /is

### OS and Versions
* Nukkit Version: 1.1.3
* Java Version: 8_131
* ASkyBlock version: Build #65

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | Windows 10 |
| Client Version | 1.1.5 |

### Crashdump, Backtrace or Other Files
no

**Comment by larryTheCoder** [comment]
You need to delete database.db and world folder. Its old and need to be renewed

**Comment by PetteriM1** [comment]
I deleted all files, but no

**Comment by larryTheCoder** [comment]
This issue are relating to safe spot position. Not freezing.
