### ISSUE TITLE
Failed to find your island safe spawn

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#28]
After server stop and start I can not go to my island.

| Item | Value |
|:----:|:-----:|
| ASkyBlock Version | Build #70 |
| Nukkit Version | 1.0dev |
| Client Edition | Windows 10 |
| Client Version | 1.1.5 |
| Java Version | 1.8.0_131 |

![image](https://user-images.githubusercontent.com/26197131/29523599-34533128-8696-11e7-9431-4409d46b8c69.JPG)

**Comment by larryTheCoder** [comment]
Your spawn position might be slightly moved to another location.

**Comment by larryTheCoder** [comment]
@PetteriM1 there several changes I made. The most part are delete island wont work :D i removed the feature to intended a new reset solution. You may need to wait several days then i added this thing :+1:
