### ISSUE TITLE
Server freezing

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#29]
When I use /is nothing happen, server freezes for a moment. I use last build.

**Comment by Adam1609** [comment]
The plugin doesn't work at the moment, but you can still help this plugin to complete if u can dev :)

**Comment by larryTheCoder** [comment]
I agreed with @Adam1609 comment. But @PetteriM1you can still wait several more days. Actually i had fixed this. The problem was the chunks. The chunk might not been loaded after server restart #28

**Comment by larryTheCoder** [comment]
Did this recent build fix your issue?

**Comment by PetteriM1** [comment]
It works! Thank you so much!
