### ISSUE TITLE
Achievements ?

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/ASkyBlock-Nukkit#3]
Achievments and island level please and all commands.. @larryTheCoder

**Comment by NycuRO** [comment]
@larryTheCoder You can add?

**Comment by larryTheCoder** [comment]
it is not Achievements it called challenges in Sky-Block.
and of course i will add it

**Comment by NycuRO** [comment]
@larryTheCoder Update ?

**Comment by NycuRO** [comment]
@larryTheCoder update?

**Comment by larryTheCoder** [comment]
@NycuRO Please wait to see this update, I know you really want it

**Comment by NycuRO** [comment]
:)
