### ISSUE TITLE
CIRCLE CI Link broken

### ISSUE THREAD

**Issue by iDirtniverse** [larryTheCoder/ASkyBlock-Nukkit#5]
Hi apparently the CIRCLE CI download link is broken, if you can please fix it ?

https://gyazo.com/8e48c9d714d8ccd7118af7f59a4d99af

**Comment by iDirtniverse** [comment]
https://gyazo.com/9ab57c43625b738258a31db305ae15e4

**Comment by larryTheCoder** [comment]
the problem was fixed
