### ISSUE TITLE
New plugin, Factions?

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/ASkyBlock-Nukkit#8]
If you have time, you can develop and one Factions Plugin?

Factions plugin for Nukkit exist, but have one error when released 1.0 in nukkit.

You can develop and this plugin: https://github.com/imjack/Factions-For-Nukkit ? 

@larryTheCoder

**Comment by iDirtniverse** [comment]
He didn't even finish the plugins he's making ATM you expecting him to make a new one already? Can you calm down a little lol ( I know you said if, just stating your eagerness )

**Comment by larryTheCoder** [comment]
@iDirtniverse lol

**Comment by XShockinFireX** [comment]
@NycuRO Please stop annoying him, he is spending his time making this plugin for us and all you do is ask for more. Keep in mind, he is busy and he can't spend all his time doing what you want him to do.
