### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CoolGuyMC** [larryTheCoder/ASkyBlock-Nukkit#9]
I love this plugin man, you're the best :D

In the latest version I get this error:

[ALERT] java.lang.RuntimeException: java.lang.IllegalAccessError: class
 org.sqlite.SQLiteConfig$TransactionMode cannot access its superinterface org.sq
lite.SQLiteConfig$PragmaValue

Ty in advance :D

**Comment by NycuRO** [comment]
@larryTheCoder

**Comment by larryTheCoder** [comment]
I didnt get this error try DbLib v0.2.1

And what type of database did you use @CoolGuyMC

**Comment by CoolGuyMC** [comment]
@larryTheCoder I'm using DbLib v0.2.1, and the database is the default, I haven't messed with that...

**Comment by larryTheCoder** [comment]
not relevant
